#!/bin/bash

# Ensure the previous startup succeeded and this actually exists.
if [ -d "${OPENSHIFT_JETTY8_DIR}/versions/8.14" ]; then
    cd ${OPENSHIFT_JETTY8_DIR}/versions/8.14/

    # Ensure the process is actually running.
    if ps -p `cat jetty.pid` > /dev/null
    then
       kill `cat jetty.pid`
    fi
fi

